sudo: false
language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - npm update -g npm
  - npm install -g bob coveralls --loglevel error
script:
  - bob build
  - cat .bob/coverage/buster-istanbul/lcov.info | coveralls
